version: "3.8"

services:
  app:
    build:
      context: .
    image: wa-server
    container_name: wa-server
    ports:
      - "8080:8080"
    depends_on:
      - wa-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-wa:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
#    deploy:
#      replicas: 3

  wa-db:
    image: postgres:16.1
    container_name: postgres-wa
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - wa-db-data:/var/lib/postgresql/data

volumes:
  wa-db-data:
